### PR TITLE
Fix cmp header sender field sorting

### LINKED ISSUE #445: CmpRevokeResponseMessage created with incorrect sender information in header
**Describe the Bug**

[RFC4210](https://www.rfc-editor.org/rfc/rfc4210#section-5.1.1) states

>    The sender field contains the name of the sender of the PKIMessage.
>    This name (in conjunction with senderKID, if supplied) should be
>    sufficient to indicate the key to use to verify the protection on the
>    message.

This is requirement is further specified in [RFC9483](https://datatracker.ietf.org/doc/html/rfc9483#section-3.1):

>  sender                      REQUIRED
>     -- Contains a name representing the originator, which also
>     --   protects the message
>     -- For signature-based protection, MUST be the subject field of
>     --   the CMP protection certificate

For `CmpRevokeResponseMessage` this is not in all cases ensured by EJBCA. In the following example the order of the fields in the sender and the subject of the first  certificate in the extracert field are reverted:

image

**To Reproduce**

Send a CMP message to EJBCA that triggers the execution of https://github.com/Keyfactor/ejbca-ce/blob/74957651b1d870ffc7796ffaa002e4c3f2be16fa/modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java#L253

instead of 

https://github.com/Keyfactor/ejbca-ce/blob/74957651b1d870ffc7796ffaa002e4c3f2be16fa/modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java#L251

**Expected Behavior**

Always embed the content of the Subject field of the signing CA as the Sender in the CMP header.

**Screenshots and Logs**

see above

**Product Deployment** 

EJBCA 8.0 Community (ce7f5e74b9a054edf61b188fa46f03e57b8478ab)

**Desktop**

n/a

**Additional Context**

n/a

### PR DESCRIPTION
**Pull request by RufusJWB**
Fixes #445

### CODE REVIEW

File: modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java [hunk 1]
```diff
@@ -234,40 +234,40 @@ public ResponseMessage handleMessage(final BaseCmpMessage msg, boolean authentic
...
 
 		if (StringUtils.equals(responseProtection, "pbe")) {
-		    final HMACAuthenticationModule hmacmodule = (HMACAuthenticationModule) authenticationModule;
+			// The revocation message may have had an empty recipient, in which case we got the recipient from the CMP configuration (see above)
+			if (StringUtils.isEmpty(msg.getRecipient().getName().toString())) {
+				final X509Certificate cacert = (X509Certificate)ca.getCACertificate();
+				final GeneralName sender = new GeneralName(X500Name.getInstance(cacert.getSubjectX500Principal().getEncoded()));
+				rresp.setSender(sender);
+			} else {
+				rresp.setSender(msg.getRecipient());
```
Comment (primetomas) [inline modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java:260]: This else statement looks redundant as "rresp.setRecipient(msg.getSender());" is set as the "default above, isn't it?

File: modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java [hunk 2]
```diff
@@ -234,40 +234,40 @@ public ResponseMessage handleMessage(final BaseCmpMessage msg, boolean authentic
...
-		}
 		rresp.setRecipient(msg.getSender());
 		rresp.setTransactionId(msg.getTransactionId());
 		rresp.setFailInfo(failInfo);
 		rresp.setFailText(failText);
 		rresp.setStatus(status);
 
 		if (StringUtils.equals(responseProtection, "pbe")) {
-		    final HMACAuthenticationModule hmacmodule = (HMACAuthenticationModule) authenticationModule;
+			// The revocation message may have had an empty recipient, in which case we got the recipient from the CMP configuration (see above)
```
Comment (primetomas) [inline modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java:254]: It would be great to add references to RFCs, as noted in the github discussion. Just a line or two of java comments. It's helpful for long term maintenance.

File: modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java [hunk 3]
```diff
@@ -292,6 +292,10 @@ public ResponseMessage handleMessage(final BaseCmpMessage msg, boolean authentic
 			}
 		} else if(StringUtils.equals(responseProtection, "signature")) {
 		    try {
+			    final X509Certificate cacert = (X509Certificate)ca.getCACertificate();
```
Comment (primetomas) [inline modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java:295]: Same here, just a reference to the RFC, and maybe a note that the recipient as sent by the sender may be the CA DN, but not byte-for-byte equal.

File: modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java (hunk 2 above)
Comment (RufusJWB) [reply modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java:254]: Done

File: modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java (hunk 3 above)
Comment (RufusJWB) [reply modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java:295]: done

File: modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java (hunk 1 above)
Comment (primetomas) [reply modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java:261]: I was wrong here, "rresp.setRecipient" vs rrsesp.setSender. I made a slight modification and moved up the "default" to remove the else statement.

**Comment by primetomas** [comment]
Looks great, reviewed, removed whitespace changes and made a small change (see comment). Waiting for CI test run before merge.

**Comment by primetomas** [comment]
@RufusJWB : would you like to be mentioned on the contributors page? https://www.ejbca.org/contributors/

**Comment by RufusJWB** [comment]
> @RufusJWB : would you like to be mentioned on the contributors page? https://www.ejbca.org/contributors/

I'd be honored. Yes!

**Comment by primetomas** [comment]
Merged to the EJBCA Enterprise 8.3.0 release, and here on GitHub.
